

def get_questions():

    return [
  {"question": "Zero-day attacks exploit vulnerabilities before developers can patch them.", "answer": True},
  {"question": "Hexadecimal numbers use 20 symbols.", "answer": False},
  {"question": "A threat is harmless unless it is exploited.", "answer": False},
  {"question": "A firewall alone is sufficient protection against malware.", "answer": False},
  {"question": "Numerical 777 means full permissions for all user classes.", "answer": True},
  {"question": "The binary number system is base-10.", "answer": False},
  {"question": "Cryptography aims to secure communication from adversaries.", "answer": True},
  {"question": "Locker ransomware completely locks devices.", "answer": True},
  {"question": "Cryptographic hash functions produce a fixed-size output.", "answer": True},
  {"question": "Viruses wait for user interaction to execute and spread.", "answer": True},
  {"question": "Retail companies are immune to cyberattacks.", "answer": False},
  {"question": "Ransomware only encrypts files but never steals them.", "answer": False},
  {"question": "Cloud governance helps organizations manage cloud resources securely.", "answer": True},
  {"question": "Public-key cryptography is another name for asymmetric cryptography.", "answer": True},
  {"question": "Threat modeling is only useful after a system has been attacked.", "answer": False},
  {"question": "Cryptanalysis is the science of securing information.", "answer": False},
  {"question": "Attack trees visualize the steps required to compromise a system.", "answer": True},
  {"question": "Cryptojacking uses a victim's device to mine cryptocurrency.", "answer": True},
  {"question": "Firewalls cannot restrict traffic based on suspicious ports.", "answer": False},
  {"question": "Social engineering involves tricking users into giving up information.", "answer": True},
  {"question": "Ransomware as a Service (RaaS) lets others rent ransomware.", "answer": True},
  {"question": "Execute permission allows reading a file.", "answer": False},
  {"question": "Hashing can be used for password security and file integrity verification.", "answer": True},
  {"question": "A Trojan horse appears to be legitimate software but is malicious.", "answer": True},
  {"question": "Worms need to attach themselves to another program to spread.", "answer": False},
  {"question": "The chmod command is used to change file permissions.", "answer": True},
  {"question": "Encryption and hashing serve the same primary purpose.", "answer": False},
  {"question": "A logic bomb activates only when specific conditions are met.", "answer": True},
  {"question": "Symmetric cryptography uses two different keys for encryption and decryption.", "answer": False},
  {"question": "Spyware can track a user's online activity and record keystrokes.", "answer": True},
  {"question": "Triple extortion ransomware may include DDoS attacks.", "answer": True},
  {"question": "Adware and spyware are both types of malware.", "answer": True},
  {"question": "Threat intelligence sharing can help detect attacks sooner.", "answer": True},
  {"question": "Vulnerabilities can arise from features, flaws, or user errors.", "answer": True},
  {"question": "Converting decimal to binary involves repeated division by 2.", "answer": True},
  {"question": "A good hash function should be collision-resistant.", "answer": True},
  {"question": "In Unix, file permissions are defined for the owner, group, and others.", "answer": True},
  {"question": "Malware is designed to improve computer system performance.", "answer": False},
  {"question": "Encryption turns plaintext into unreadable ciphertext.", "answer": True},
  {"question": "Only root can change file permissions in Unix.", "answer": True},
  {"question": "Healthcare data is not a significant target for cyberattacks.", "answer": False},
  {"question": "Hashing is a reversible process used to protect data.", "answer": False},
  {"question": "Firewalls can block known malicious IP addresses.", "answer": True},
  {"question": "The decimal equivalent of binary 101101 is 45.", "answer": True},
  {"question": "ASCII uses 7 bits to represent characters.", "answer": True}
]
